# Generated by Django 4.2 on 2024-01-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
