# Generated by Django 4.2 on 2024-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_create_date_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('none', 'Отсутствует'), ('in_progress', 'В работе'), ('done', 'Выполнен'), ('not_done', 'Не выполнен'), ('canceled', 'Отменен')], default='none', max_length=20, verbose_name='Статус'),
        ),
    ]
