# Generated by Django 4.2 on 2024-01-28 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subordinates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superior',
        ),
        migrations.AddField(
            model_name='user',
            name='superiors',
            field=models.ManyToManyField(related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
