# Generated by Django 4.2 on 2024-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='subordinates',
            field=models.BooleanField(default=True, verbose_name='Cотрудник'),
        ),
        migrations.AddField(
            model_name='user',
            name='superior',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
    ]
