# Generated by Django 4.2 on 2024-01-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(max_length=50, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/photos", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=150, verbose_name="Должность"),
        ),
        migrations.AlterField(
            model_name="user",
            name="subordinates",
            field=models.BooleanField(default=True, verbose_name="Cотрудник"),
        ),
    ]
