# Generated by Django 4.2 on 2024-01-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo_user_subordinates_user_superior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subordinates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superior',
        ),
    ]
