# Generated by Django 4.2 on 2024-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_subordinates_remove_user_superior_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="users/default-photo.jpg",
                null=True,
                upload_to="users",
                verbose_name="Фото",
            ),
        ),
    ]
