# Generated by Django 4.2 on 2024-01-24 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_patronymic_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subordinates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superior',
        ),
        migrations.AddField(
            model_name='user',
            name='subordinates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подчиненные'),
        ),
        migrations.AddField(
            model_name='user',
            name='superior',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Руководители'),
        ),
    ]
