# Generated by Django 4.2 on 2024-01-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ipr',
        ),
    ]
