# Generated by Django 4.2 on 2024-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprs', '0003_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
