# Generated by Django 4.2 on 2024-01-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iprs', '0004_remove_task_deadline_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ipr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_ipr', to='iprs.ipr', verbose_name='ИПР'),
            preserve_default=False,
        ),
    ]
