# Generated by Django 4.2 on 2024-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprs', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default='2024-12-12', verbose_name='Плановое время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default='2024-12-12', verbose_name='Дата завершения'),
            preserve_default=False,
        ),
    ]
