# Generated by Django 4.2 on 2024-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iprs", "0007_task_start_date_alter_task_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipr",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Не начат"),
                    ("In progress", "В работе"),
                    ("Done", "Выполнен"),
                    ("Failed", "Не выполнен"),
                    ("Canceled", "Отменен"),
                    ("No status", "Отсутствует"),
                ],
                default="No status",
                max_length=11,
                verbose_name="Статус ИПР",
            ),
        ),
    ]
